#[derive(Debug, Clone, PartialEq)]
pub enum FuelPhase {
    Liquid,
    Gaseous,
}

#[derive(Debug, Clone)]
pub struct Fuel {
    pub name: &'static str,
    pub phase: FuelPhase,
    /// Lower Heating Value (standardized), MJ/liter or MJ/m³
    pub lhv_standardized: f64,
    /// Lower Heating Value, MJ/liter or MJ/m³
    pub lhv: f64,
    /// Higher Heating Value, MJ/liter or MJ/m³
    pub hhv: f64,
    /// Density, g/liter or g/m³
    pub density_grams_per_liter: f64,
    /// Energy density, MJ/kg
    pub energy_density_mj_per_kg: f64,
}

pub const FUELS: &[Fuel] = &[
    // ── Liquid Fuels ─────────────────────────────────────────────────────────
    Fuel {
        name: "Crude oil",
        phase: FuelPhase::Liquid,
        lhv_standardized: 36.14,
        lhv: 36.14,
        hhv: 38.56,
        density_grams_per_liter: 847.0,
        energy_density_mj_per_kg: 42.7,
    },
    Fuel {
        name: "Synthetic crude oil (SCO)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 37.65,
        lhv: 37.65,
        hhv: 40.27,
        density_grams_per_liter: 863.0,
        energy_density_mj_per_kg: 43.6,
    },
    Fuel {
        name: "Bitumen",
        phase: FuelPhase::Liquid,
        lhv_standardized: 42.47,
        lhv: 42.47,
        hhv: 45.42,
        density_grams_per_liter: 1014.0,
        energy_density_mj_per_kg: 41.9,
    },
    Fuel {
        name: "Dilbit (After Recovery)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 42.47,
        lhv: 42.47,
        hhv: 45.42,
        density_grams_per_liter: 1014.0,
        energy_density_mj_per_kg: 41.9,
    },
    Fuel {
        name: "Dilbit (Before Recovery)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 40.47,
        lhv: 40.47,
        hhv: 43.28,
        density_grams_per_liter: 925.0,
        energy_density_mj_per_kg: 43.8,
    },
    Fuel {
        name: "Diluent",
        phase: FuelPhase::Liquid,
        lhv_standardized: 35.80,
        lhv: 35.80,
        hhv: 38.29,
        density_grams_per_liter: 716.0,
        energy_density_mj_per_kg: 50.0,
    },
    Fuel {
        name: "Shale Oil (Bakken)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 35.01,
        lhv: 35.01,
        hhv: 37.35,
        density_grams_per_liter: 816.0,
        energy_density_mj_per_kg: 42.9,
    },
    Fuel {
        name: "Shale Oil (Eagle Ford)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.14,
        lhv: 34.14,
        hhv: 36.43,
        density_grams_per_liter: 788.0,
        energy_density_mj_per_kg: 43.3,
    },
    Fuel {
        name: "Gasoline blendstock",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.36,
        lhv: 32.36,
        hhv: 34.66,
        density_grams_per_liter: 745.0,
        energy_density_mj_per_kg: 43.4,
    },
    Fuel {
        name: "Gasoline",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.27,
        lhv: 31.27,
        hhv: 33.57,
        density_grams_per_liter: 749.0,
        energy_density_mj_per_kg: 41.7,
    },
    Fuel {
        name: "CA gasoline",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.27,
        lhv: 31.27,
        hhv: 33.57,
        density_grams_per_liter: 749.0,
        energy_density_mj_per_kg: 41.7,
    },
    Fuel {
        name: "High Octane Fuel (E25)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 29.59,
        lhv: 29.59,
        hhv: 31.88,
        density_grams_per_liter: 756.0,
        energy_density_mj_per_kg: 39.1,
    },
    Fuel {
        name: "High Octane Fuel (E40)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 27.92,
        lhv: 27.92,
        hhv: 30.22,
        density_grams_per_liter: 763.0,
        energy_density_mj_per_kg: 36.6,
    },
    Fuel {
        name: "U.S. conventional diesel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 35.80,
        lhv: 35.80,
        hhv: 38.29,
        density_grams_per_liter: 837.0,
        energy_density_mj_per_kg: 42.8,
    },
    Fuel {
        name: "CA diesel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 36.09,
        lhv: 36.09,
        hhv: 38.60,
        density_grams_per_liter: 847.0,
        energy_density_mj_per_kg: 42.6,
    },
    Fuel {
        name: "Diesel for non-road engines",
        phase: FuelPhase::Liquid,
        lhv_standardized: 35.80,
        lhv: 35.80,
        hhv: 38.29,
        density_grams_per_liter: 837.0,
        energy_density_mj_per_kg: 42.8,
    },
    Fuel {
        name: "Low-sulfur diesel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 36.09,
        lhv: 36.09,
        hhv: 38.60,
        density_grams_per_liter: 847.0,
        energy_density_mj_per_kg: 42.6,
    },
    Fuel {
        name: "Petroleum naphtha",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.59,
        lhv: 32.59,
        hhv: 34.86,
        density_grams_per_liter: 725.0,
        energy_density_mj_per_kg: 44.9,
    },
    Fuel {
        name: "Low Octane Gasoline-Like Fuel (LOF)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.95,
        lhv: 32.95,
        hhv: 35.28,
        density_grams_per_liter: 749.0,
        energy_density_mj_per_kg: 44.0,
    },
    Fuel {
        name: "Conventional Jet Fuel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.65,
        lhv: 34.65,
        hhv: 37.05,
        density_grams_per_liter: 802.0,
        energy_density_mj_per_kg: 43.2,
    },
    Fuel {
        name: "ULS Jet Fuel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.29,
        lhv: 34.29,
        hhv: 36.68,
        density_grams_per_liter: 792.0,
        energy_density_mj_per_kg: 43.3,
    },
    Fuel {
        name: "NG-based FT naphtha",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.08,
        lhv: 31.08,
        hhv: 33.37,
        density_grams_per_liter: 700.0,
        energy_density_mj_per_kg: 44.4,
    },
    Fuel {
        name: "Residual oil",
        phase: FuelPhase::Liquid,
        lhv_standardized: 39.12,
        lhv: 39.12,
        hhv: 41.84,
        density_grams_per_liter: 991.0,
        energy_density_mj_per_kg: 39.5,
    },
    Fuel {
        name: "Bunker fuel for ocean tanker",
        phase: FuelPhase::Liquid,
        lhv_standardized: 39.12,
        lhv: 39.12,
        hhv: 41.84,
        density_grams_per_liter: 991.0,
        energy_density_mj_per_kg: 39.5,
    },
    Fuel {
        name: "Methanol",
        phase: FuelPhase::Liquid,
        lhv_standardized: 15.96,
        lhv: 15.96,
        hhv: 18.17,
        density_grams_per_liter: 794.0,
        energy_density_mj_per_kg: 20.094,
    },
    Fuel {
        name: "Ethanol",
        phase: FuelPhase::Liquid,
        lhv_standardized: 21.27,
        lhv: 21.27,
        hhv: 23.56,
        density_grams_per_liter: 789.0,
        energy_density_mj_per_kg: 27.0,
    },
    Fuel {
        name: "Butanol",
        phase: FuelPhase::Liquid,
        lhv_standardized: 27.83,
        lhv: 27.83,
        hhv: 30.23,
        density_grams_per_liter: 810.0,
        energy_density_mj_per_kg: 34.4,
    },
    Fuel {
        name: "Acetone",
        phase: FuelPhase::Liquid,
        lhv_standardized: 23.17,
        lhv: 23.17,
        hhv: 24.95,
        density_grams_per_liter: 783.0,
        energy_density_mj_per_kg: 29.6,
    },
    Fuel {
        name: "EtOH-Diesel Additives",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.36,
        lhv: 32.36,
        hhv: 34.66,
        density_grams_per_liter: 745.0,
        energy_density_mj_per_kg: 43.4,
    },
    Fuel {
        name: "Liquefied petroleum gas (LPG)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 23.68,
        lhv: 23.68,
        hhv: 25.48,
        density_grams_per_liter: 508.0,
        energy_density_mj_per_kg: 46.6,
    },
    Fuel {
        name: "Liquefied natural gas (LNG)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 20.83,
        lhv: 20.83,
        hhv: 23.64,
        density_grams_per_liter: 428.0,
        energy_density_mj_per_kg: 48.6,
    },
    Fuel {
        name: "Dimethyl ether (DME)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 19.21,
        lhv: 19.21,
        hhv: 21.07,
        density_grams_per_liter: 665.0,
        energy_density_mj_per_kg: 28.9,
    },
    Fuel {
        name: "Dimethoxy methane (DMM)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 20.12,
        lhv: 20.12,
        hhv: 22.07,
        density_grams_per_liter: 860.0,
        energy_density_mj_per_kg: 23.4,
    },
    Fuel {
        name: "Methyl ester (biodiesel, BD)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 33.34,
        lhv: 33.34,
        hhv: 35.66,
        density_grams_per_liter: 881.0,
        energy_density_mj_per_kg: 37.841,
    },
    Fuel {
        name: "Fischer-Tropsch diesel (FTD)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.47,
        lhv: 34.47,
        hhv: 36.24,
        density_grams_per_liter: 797.0,
        energy_density_mj_per_kg: 43.2,
    },
    Fuel {
        name: "Renewable Diesel I (SuperCetane)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.63,
        lhv: 32.63,
        hhv: 34.90,
        density_grams_per_liter: 749.0,
        energy_density_mj_per_kg: 43.6,
    },
    Fuel {
        name: "Renewable Diesel II (UOP-HDO)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.25,
        lhv: 34.25,
        hhv: 36.46,
        density_grams_per_liter: 778.78,
        energy_density_mj_per_kg: 43.980,
    },
    Fuel {
        name: "Renewable Diesel III (PNNL-HTL)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.43,
        lhv: 34.43,
        hhv: 37.09,
        density_grams_per_liter: 793.0,
        energy_density_mj_per_kg: 43.4,
    },
    Fuel {
        name: "Renewable Diesel IV (Sludge HTL)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.68,
        lhv: 34.68,
        hhv: 34.68,
        density_grams_per_liter: 798.0,
        energy_density_mj_per_kg: 43.5,
    },
    Fuel {
        name: "Renewable Gasoline",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.33,
        lhv: 32.33,
        hhv: 34.62,
        density_grams_per_liter: 748.0,
        energy_density_mj_per_kg: 43.2,
    },
    Fuel {
        name: "Renewable Gasoline (IDL)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.58,
        lhv: 31.58,
        hhv: 33.83,
        density_grams_per_liter: 717.0,
        energy_density_mj_per_kg: 44.1,
    },
    Fuel {
        name: "Renewable Gasoline (Ex Situ CFP)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.23,
        lhv: 31.23,
        hhv: 33.45,
        density_grams_per_liter: 745.0,
        energy_density_mj_per_kg: 41.9,
    },
    Fuel {
        name: "SPK (FT Jet Fuel/HRJ)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 33.38,
        lhv: 33.38,
        hhv: 35.70,
        density_grams_per_liter: 757.0,
        energy_density_mj_per_kg: 44.1,
    },
    Fuel {
        name: "Liquid hydrogen",
        phase: FuelPhase::Liquid,
        lhv_standardized: 8.50,
        lhv: 8.50,
        hhv: 10.04,
        density_grams_per_liter: 711.0,
        energy_density_mj_per_kg: 120.1,
    },
    Fuel {
        name: "Methyl tertiary butyl ether (MTBE)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 26.07,
        lhv: 26.07,
        hhv: 28.19,
        density_grams_per_liter: 743.0,
        energy_density_mj_per_kg: 35.1,
    },
    Fuel {
        name: "Ethyl tertiary butyl ether (ETBE)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 26.96,
        lhv: 26.96,
        hhv: 29.13,
        density_grams_per_liter: 742.0,
        energy_density_mj_per_kg: 36.3,
    },
    Fuel {
        name: "Tertiary amyl methyl ether (TAME)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 28.01,
        lhv: 28.01,
        hhv: 30.26,
        density_grams_per_liter: 770.0,
        energy_density_mj_per_kg: 36.4,
    },
    Fuel {
        name: "Butane",
        phase: FuelPhase::Liquid,
        lhv_standardized: 26.47,
        lhv: 26.47,
        hhv: 28.77,
        density_grams_per_liter: 585.0,
        energy_density_mj_per_kg: 45.3,
    },
    Fuel {
        name: "Isobutane",
        phase: FuelPhase::Liquid,
        lhv_standardized: 25.10,
        lhv: 25.10,
        hhv: 27.47,
        density_grams_per_liter: 560.0,
        energy_density_mj_per_kg: 44.9,
    },
    Fuel {
        name: "Isobutylene",
        phase: FuelPhase::Liquid,
        lhv_standardized: 26.68,
        lhv: 26.68,
        hhv: 28.71,
        density_grams_per_liter: 595.0,
        energy_density_mj_per_kg: 44.8,
    },
    Fuel {
        name: "Propane",
        phase: FuelPhase::Liquid,
        lhv_standardized: 23.48,
        lhv: 23.48,
        hhv: 25.48,
        density_grams_per_liter: 507.0,
        energy_density_mj_per_kg: 46.3,
    },
    Fuel {
        name: "Natural gas liquids",
        phase: FuelPhase::Liquid,
        lhv_standardized: 23.32,
        lhv: 23.32,
        hhv: 25.10,
        density_grams_per_liter: 669.0,
        energy_density_mj_per_kg: 34.9,
    },
    Fuel {
        name: "n-Hexane",
        phase: FuelPhase::Liquid,
        lhv_standardized: 29.30,
        lhv: 29.30,
        hhv: 31.26,
        density_grams_per_liter: 655.0,
        energy_density_mj_per_kg: 44.7,
    },
    Fuel {
        name: "E_fuel Gasoline BOB",
        phase: FuelPhase::Liquid,
        lhv_standardized: 30.87,
        lhv: 30.87,
        hhv: 32.67,
        density_grams_per_liter: 689.0,
        energy_density_mj_per_kg: 44.8,
    },
    Fuel {
        name: "E_fuel Jet",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.60,
        lhv: 32.60,
        hhv: 34.64,
        density_grams_per_liter: 738.0,
        energy_density_mj_per_kg: 44.2,
    },
    Fuel {
        name: "E_fuel Diesel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 33.67,
        lhv: 33.67,
        hhv: 35.74,
        density_grams_per_liter: 765.0,
        energy_density_mj_per_kg: 44.0,
    },
    Fuel {
        name: "E_fuel FT mixed fuel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.41,
        lhv: 32.41,
        hhv: 34.39,
        density_grams_per_liter: 732.0,
        energy_density_mj_per_kg: 44.3,
    },
    Fuel {
        name: "Isobutanol",
        phase: FuelPhase::Liquid,
        lhv_standardized: 26.56,
        lhv: 26.56,
        hhv: 29.46,
        density_grams_per_liter: 800.0,
        energy_density_mj_per_kg: 33.2,
    },
    Fuel {
        name: "ARHC",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.33,
        lhv: 32.33,
        hhv: 34.62,
        density_grams_per_liter: 748.0,
        energy_density_mj_per_kg: 43.2,
    },
    Fuel {
        name: "Isoalkane from waste feedstock",
        phase: FuelPhase::Liquid,
        lhv_standardized: 37.20,
        lhv: 34.60,
        hhv: 37.20,
        density_grams_per_liter: 779.0,
        energy_density_mj_per_kg: 47.7,
    },
    Fuel {
        name: "Fatty alkyl ether (FAE)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 37.48,
        lhv: 35.00,
        hhv: 37.48,
        density_grams_per_liter: 840.0,
        energy_density_mj_per_kg: 44.6,
    },
    Fuel {
        name: "FAFE (Fatty acid fusel ester)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 36.23,
        lhv: 34.00,
        hhv: 36.23,
        density_grams_per_liter: 839.0,
        energy_density_mj_per_kg: 43.2,
    },
    Fuel {
        name: "HTL - Partial Upgrading (Sludge)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 41.36,
        lhv: 41.36,
        hhv: 0.00,
        density_grams_per_liter: 961.0,
        energy_density_mj_per_kg: 43.0,
    },
    Fuel {
        name: "HTL - Partial Upgrading (Manure)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 40.81,
        lhv: 40.81,
        hhv: 0.00,
        density_grams_per_liter: 963.0,
        energy_density_mj_per_kg: 42.4,
    },
    Fuel {
        name: "FP (Biomass)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 19.95,
        lhv: 19.95,
        hhv: 0.00,
        density_grams_per_liter: 1198.0,
        energy_density_mj_per_kg: 16.7,
    },
    Fuel {
        name: "CFP - ZSM5 (Biomass)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 30.79,
        lhv: 30.79,
        hhv: 0.00,
        density_grams_per_liter: 975.0,
        energy_density_mj_per_kg: 31.6,
    },
    Fuel {
        name: "CFP (Pt/TiO2)",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.42,
        lhv: 31.42,
        hhv: 0.00,
        density_grams_per_liter: 971.0,
        energy_density_mj_per_kg: 32.4,
    },
    Fuel {
        name: "Pyrolysis diesel",
        phase: FuelPhase::Liquid,
        lhv_standardized: 34.37,
        lhv: 34.37,
        hhv: 0.00,
        density_grams_per_liter: 832.0,
        energy_density_mj_per_kg: 41.3,
    },
    Fuel {
        name: "FT-Gasoline-Nuclear",
        phase: FuelPhase::Liquid,
        lhv_standardized: 30.19,
        lhv: 30.19,
        hhv: 32.60,
        density_grams_per_liter: 687.0,
        energy_density_mj_per_kg: 44.0,
    },
    Fuel {
        name: "FT-Jet-Nuclear",
        phase: FuelPhase::Liquid,
        lhv_standardized: 32.69,
        lhv: 32.69,
        hhv: 35.15,
        density_grams_per_liter: 741.0,
        energy_density_mj_per_kg: 44.1,
    },
    Fuel {
        name: "FT-Diesel-Nuclear",
        phase: FuelPhase::Liquid,
        lhv_standardized: 33.77,
        lhv: 33.77,
        hhv: 36.31,
        density_grams_per_liter: 769.0,
        energy_density_mj_per_kg: 43.9,
    },
    Fuel {
        name: "FT-Fuel Mix-Nuclear",
        phase: FuelPhase::Liquid,
        lhv_standardized: 31.02,
        lhv: 31.02,
        hhv: 33.41,
        density_grams_per_liter: 705.0,
        energy_density_mj_per_kg: 44.0,
    },
    Fuel {
        name: "Ammonia",
        phase: FuelPhase::Liquid,
        lhv_standardized: 11.31,
        lhv: 11.31,
        hhv: 11.31,
        density_grams_per_liter: 603.0,
        energy_density_mj_per_kg: 18.8,
    },
    // ── Gaseous Fuels (at 32 °F / 0 °C, 1 atm) ───────────────────────────────
    Fuel {
        name: "Natural gas",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 36.63,
        lhv: 36.63,
        hhv: 40.57,
        density_grams_per_liter: 777.0,
        energy_density_mj_per_kg: 47.1,
    },
    Fuel {
        name: "Renewable Natural Gas",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 36.63,
        lhv: 36.63,
        hhv: 40.57,
        density_grams_per_liter: 777.0,
        energy_density_mj_per_kg: 47.1,
    },
    Fuel {
        name: "Synthetic NG (SNG)",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 35.73,
        lhv: 35.73,
        hhv: 39.67,
        density_grams_per_liter: 717.0,
        energy_density_mj_per_kg: 49.9,
    },
    Fuel {
        name: "Pure Methane",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 35.85,
        lhv: 35.85,
        hhv: 39.79,
        density_grams_per_liter: 717.0,
        energy_density_mj_per_kg: 50.0,
    },
    Fuel {
        name: "Gaseous hydrogen",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 10.81,
        lhv: 10.81,
        hhv: 12.78,
        density_grams_per_liter: 901.0,
        energy_density_mj_per_kg: 120.0,
    },
    Fuel {
        name: "Carbon Dioxide",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 0.00,
        lhv: 0.00,
        hhv: 0.00,
        density_grams_per_liter: 1977.0,
        energy_density_mj_per_kg: 0.0,
    },
    Fuel {
        name: "Still gas (in refineries)",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 43.19,
        lhv: 43.19,
        hhv: 47.68,
        density_grams_per_liter: 884.0,
        energy_density_mj_per_kg: 48.9,
    },
    Fuel {
        name: "Fuel gas (ATR)",
        phase: FuelPhase::Gaseous,
        lhv_standardized: 10.71,
        lhv: 10.71,
        hhv: 12.52,
        density_grams_per_liter: 600.0,
        energy_density_mj_per_kg: 17.9,
    },
];

//
//Input {
//    value: 4000000
//    Unit: t
//}
//
//
//
//convert 4 Million tonnes of diesel into m3 of diesel
//
//
//1 * 1000 * 1000  = in grams
//
//732.0 g => liters
//1 * 1000 * 1000 =>
//
//1 * 1000 * 1000 / 732.0
//
//
//732 / 1000
